[phases.setup]
nixPkgs = ['openjdk17']

[phases.build]
cmds = [
  'find . -type f -name "gradlew" -exec chmod +x {} \;',
  'find . -type f -name "gradlew" -exec {} build \;'
]

[start]
cmd = 'find . -type f -name "*.jar" -path "*/build/libs/*" -exec java -jar {} \;'
